spring:
  application:
    name: "Chartreuse shop"

  data:
    mongodb:
      uri: "mongodb://localhost:27017/chartreuse-db"

  kafka:
    bootstrap-servers: "localhost:9092"

  modulith:
    republish-outstanding-events-on-restart: true

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  defaults:
    metrics:
      export:
        enabled: false
  metrics:
    mongo:
      command:
        enabled: false # disable springboot autoconfigured command listener; command are monitored by tracing
  tracing:
    enabled: true
    sampling:
      probability: 1
  opentelemetry:
    resource-attributes:
      environment: "local"
      "service.name": ${spring.application.name}
      "instrumentation.provider": "micrometer"
  otlp:
    metrics:
      export:
        enabled: true
        url: "http://localhost:4318/v1/metrics"
    tracing:
      endpoint: "http://localhost:4318/v1/traces"
